
known_file_types = {
    ".csv": "excel",
    ".das": "deepriser",
    ".dat": "dat",
    ".db": "database",
    ".doc": "word",
    ".docx": "word",
    ".exe": "exe",
    ".f06": "f06",
    ".ipynb": "notebook",
    ".jpeg": "image",
    ".jpg": "image",
    ".json": "json",
    ".keyx": "key_file",
    ".mkv": "video",
    ".mp3": "audio",
    ".mp4": "video",
    ".mplt": "video",
    ".msg": "msg",
    ".out": "generic",
    ".op2": "op2",
    ".pdf": "pdf",
    ".png": "image",
    ".pptx": "pptx",
    ".py": "python",
    ".rar": "rar",
    ".torrent": "torrent",
    ".txt": "text",
    ".xls": "excel",
    ".xlsm": "excel",
    ".xlsx": "excel",
    ".xmcd": "mathcad",
    ".zip": "zip",
    ".xxx": "branch"  # dummy extension for branch icon
}
# files_icons_map = {
#     "excel": self.excel_icon2,
#     "image": self.image_icon2,
#     "pdf": self.pdf_icon2,
#     "python": self.python_icon2,
#     "video": self.video_icon2,
#     "audio": self.audio_icon2,
#     "zip": self.zip_icon2,
#     "branch": self.branch_icon2,
#     "generic": self.new_icon2,
# }
